layout: {zmk_keyboard: base}
layers:
  base:
    - '`'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '0'
    - {type: trans}
    - Esc
    - Q
    - W
    - E
    - R
    - T
    - Y
    - U
    - I
    - O
    - P
    - Bspc
    - Tab
    - {t: A, h: Gui}
    - {t: S, h: Alt}
    - {t: D, h: Shift}
    - {t: F, h: Ctrl}
    - G
    - H
    - {t: J, h: Ctrl}
    - {t: K, h: Shift}
    - {t: L, h: Alt}
    - {t: ;, h: Gui}
    - ''''
    - {type: trans}
    - Z
    - X
    - C
    - V
    - B
    - $$mdi:volume-off$$
    - {type: trans}
    - N
    - M
    - ','
    - .
    - /
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {t: Spc, h: nav, s: Sentence}
    - {t: Enter, h: fn}
    - {t: Numword, h: num, s: Sticky Num}
    - {t: Magic, h: Shift}
    - AltGr
    - {type: trans}
    - {type: trans}
  nav:
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - Mouse →
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - Mouse ←
    - Mouse ↓
    - Mouse →
    - {type: trans}
    - ←
    - ↓
    - ↑
    - →
    - Del
    - Bspc
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - Left Click
    - Middle Click
    - Right Click
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: held}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
  fn:
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - F12
    - F7
    - F8
    - F9
    - {type: trans}
    - {type: trans}
    - $$mdi:skip-backward$$
    - $$mdi:volume-high$$
    - $$mdi:skip-forward$$
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {t: F11, h: Gui}
    - {t: F4, h: Alt}
    - {t: F5, h: Shift}
    - {t: F6, h: Ctrl}
    - {type: trans}
    - {type: trans}
    - {t: Prev Desk, h: Ctrl}
    - {t: '$$mdi:volume-medium$$', h: Shift}
    - {t: Next Desk, h: Alt}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - F10
    - F1
    - F2
    - F3
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: held}
    - {type: trans}
    - $$mdi:volume-off$$
    - $$mdi:play-pause$$
    - {type: trans}
    - {type: trans}
  num:
    - {type: trans}
    - F1
    - F2
    - F3
    - F4
    - F5
    - F6
    - F7
    - F8
    - F9
    - F10
    - F11
    - '`'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '0'
    - F12
    - {type: trans}
    - {t: '!', h: Gui}
    - {t: '@', h: Alt}
    - {t: '#', h: Shift}
    - {t: $, h: Ctrl}
    - '%'
    - ^
    - '&'
    - '*'
    - (
    - )
    - '|'
    - {type: trans}
    - '='
    - '-'
    - +
    - '{'
    - '}'
    - {type: trans}
    - {type: trans}
    - {t: '[', right: '{'}
    - {t: ']', right: '}'}
    - ;
    - ':'
    - \
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: held}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
  sys:
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - BT 1
    - BT 2
    - BT 3
    - BT 4
    - BT CLR
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - EP TOG
    - Boot
    - Boot
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - Reset
    - {type: trans}
    - {type: trans}
    - Reset
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: held}
    - {type: held}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
  mouse:
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - Mouse ↑
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - Mouse ↑
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - Scroll ←
    - Mouse ←
    - Mouse ↓
    - Mouse →
    - Scroll →
    - Scroll ←
    - Mouse ←
    - Mouse ↓
    - Mouse →
    - Scroll →
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - Left Click
    - Middle Click
    - Right Click
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - Scroll ↓
    - Scroll ↑
    - {type: trans}
    - {type: trans}
    - Scroll ↑
    - Scroll ↓
    - {type: trans}
    - {type: trans}
  Combos: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '']
combos:
  - p: [14, 15]
    k: Esc
    l: [Combos]
  - p: [15, 16]
    k: Smart Mouse
    l: [Combos]
  - p: [26, 27]
    k: Tab
    l: [Combos]
  - p: [27, 28]
    k: Leader
    l: [Combos]
  - p: [19, 20]
    k: Bspc
    l: [Combos]
  - p: [20, 21]
    k: Del
    l: [Combos]
  - p: [31, 32]
    k: {t: (, right: <}
    l: [Combos]
  - p: [32, 33]
    k: {t: ), right: '>'}
    l: [Combos]
  - p: [31, 32]
    k: <
    l: [Combos]
    hidden: true
  - p: [32, 33]
    k: '>'
    l: [Combos]
    hidden: true
  - p: [45, 46]
    k: {t: '[', right: '{'}
    l: [Combos]
  - p: [46, 47]
    k: {t: ']', right: '}'}
    l: [Combos]
  - p: [45, 46]
    k: '{'
    l: [Combos]
    hidden: true
  - p: [46, 47]
    k: '}'
    l: [Combos]
    hidden: true
  - p: [14, 26]
    k: '@'
    l: [Combos]
  - p: [15, 27]
    k: '#'
    l: [Combos]
  - p: [16, 28]
    k: $
    l: [Combos]
  - p: [17, 29]
    k: '%'
    l: [Combos]
  - p: [26, 38]
    k: '`'
    l: [Combos]
  - p: [27, 39]
    k: \
    l: [Combos]
  - p: [28, 40]
    k: '='
    l: [Combos]
  - p: [29, 41]
    k: '~'
    l: [Combos]
  - p: [18, 30]
    k: ^
    l: [Combos]
  - p: [19, 31]
    k: +
    l: [Combos]
  - p: [20, 32]
    k: '*'
    l: [Combos]
  - p: [21, 33]
    k: '&'
    l: [Combos]
  - p: [30, 44]
    k: _
    l: [Combos]
  - p: [31, 45]
    k: '-'
    l: [Combos]
  - p: [32, 46]
    k: /
    l: [Combos]
  - p: [33, 47]
    k: '|'
    l: [Combos]
